
// MAXIMAL AGENT-GENERATED CAD MODEL
// Generated by capability-discovery test

$fn = 96;

// Fuselage
module fuselage() {
    cylinder(h=30, r=2);
}

// Wing
module wing() {
    translate([-14.0, 0, 7.5])
        cube([28, 4, 0.6]);
}

// Tail
module tail() {
    translate([-5.0, 0, 24.0])
        cube([10, 3, 0.5]);
}

union() {
    fuselage();
    wing();
    tail();
}
