
// AUTO-GENERATED BY cad-agent FULL SYSTEM TEST

$fn = 64;

// Fuselage
translate([0,0,0])
cylinder(h=30, r=2);

// Wing
translate([-14,0,5])
cube([28,4,0.5]);

// Tail
translate([-5,0,25])
cube([10,3,0.4]);
