// =====================================
// Generated by Autonomous CAD Agent
// Geometry Engine v5.0 (Aero-Structural)
// =====================================

$fn = 128;


union() {
  cylinder(r=6.0, h=30.0, center=true);
  translate([0,0,6.0])
  cylinder(h=12.0, r1=6.0, r2=0);

  cylinder(h=30.0, r1=6.0, r2=4.5, center=true);

  translate([0,0,-15.0])
  cylinder(h=10.0, r1=4.199999999999999, r2=1.2000000000000002);
}
