// ========================================
// a cylinder radius 0.3 height 1.2
// Generated by cad-agent text-to-CAD
// ========================================
$fn = 96;

union() {
  // component: body (body)
  cylinder(r=0.3, h=1.2, center=true);
}
