"""Core text-to-CAD package.

This package contains the structured prompt parser, graph model,
and OpenSCAD exporter used by the higher level entry points.
"""

from .agentic import (
    AgentAssumption,
    AgentComponent,
    AgentPlan,
    AgentRunResult,
    AgentWorkspace,
    BuiltinPlanningProvider,
    OpenAICompatiblePlanningProvider,
    parse_agent_plan,
    plan_to_program,
    planning_provider,
    program_preview_svg,
)
from .calibration import (
    AxisObservation,
    CalibrationApplicationPlan,
    CalibrationDataset,
    CalibrationProfile,
    ClearanceObservation,
    HoleObservation,
    apply_calibrated_clearance,
    fit_calibration_profile,
    parse_calibration_dataset,
    parse_calibration_profile,
    plan_calibration_application,
    serialize_calibration_dataset,
    serialize_calibration_profile,
)
from .design_graph import Component, Connection, DesignGraph
from .edit_language import EditInterpretationError, edit_project_from_text
from .enclosure import (
    CutoutSpec,
    EnclosureBuild,
    EnclosureSpec,
    HardwareProfile,
    LidSpec,
    ManufacturingProfile,
    PCBSpec,
    SpecValidationReport,
    StandoffSpec,
    VentPatternSpec,
    build_enclosure,
    validate_enclosure_spec,
)
from .engineering_math import (
    CantileverResult,
    LayoutItem,
    LayoutPlacement,
    OrientationCandidate,
    QuadraticToleranceStack,
    ScoredOrientation,
    ToleranceContribution,
    ToleranceStack,
    ToleranceTerm,
    pack_rectangles,
    quadratic_tolerance_stack,
    rectangular_cantilever,
    score_orientations,
    symmetric_positions,
    tolerance_stack,
)
from .geometry import Primitive, box, cone, cylinder, sphere, torus
from .ir import CADProgram, Node, Transform, validate_program
from .ir import Constraint as IRConstraint
from .ir import Primitive as IRPrimitive
from .ir_adapter import design_graph_to_ir
from .ir_export import program_to_scad
from .ir_parser import IRParseError, parse_ir_json, serialize_ir_json
from .manufacturing import PreflightReport, fabrication_preflight
from .natural_language import IntentInterpretation, interpret_enclosure, interpret_provider_payload
from .physics import (
    EulerBucklingInput,
    InternalPipeFlowInput,
    SteadyConductionInput,
    ThermalExpansionInput,
    ThinWallCylinderInput,
    euler_buckling,
    internal_pipe_flow,
    steady_conduction,
    thermal_expansion,
    thin_wall_cylinder,
)
from .project import (
    EnclosureProject,
    ProjectFormatError,
    parse_project,
    read_project,
    semantic_diff,
    serialize_project,
    update_project,
    write_project,
)
from .prompt_engine import generate_design
from .scad_export import design_to_scad
from .scientific_kernel import (
    Dimension,
    Interval,
    Jet,
    NonlinearConstraint,
    Quantity,
    Unit,
    jet_cos,
    jet_exp,
    jet_log,
    jet_sin,
    jet_sqrt,
    linear_system_diagnostics,
    minimize_constrained,
    monte_carlo_propagate,
    parse_unit,
    quantity,
    solve_nonlinear_constraints,
    value_gradient_hessian,
)
from .semantic_equivalence import (
    program_semantic_form,
    program_semantic_sha256,
    programs_semantically_equivalent,
)
from .validation import ValidationReport, validate_design
from .workflow import BuildBundle, build_project_bundle, project_from_text

__all__ = [
    "AgentAssumption",
    "AgentComponent",
    "AgentPlan",
    "AgentRunResult",
    "AgentWorkspace",
    "AxisObservation",
    "BuildBundle",
    "BuiltinPlanningProvider",
    "CADProgram",
    "CalibrationApplicationPlan",
    "CalibrationDataset",
    "CalibrationProfile",
    "CantileverResult",
    "ClearanceObservation",
    "Component",
    "Connection",
    "CutoutSpec",
    "DesignGraph",
    "Dimension",
    "EditInterpretationError",
    "EnclosureBuild",
    "EnclosureProject",
    "EnclosureSpec",
    "EulerBucklingInput",
    "HardwareProfile",
    "HoleObservation",
    "IRConstraint",
    "IRParseError",
    "IRPrimitive",
    "IntentInterpretation",
    "InternalPipeFlowInput",
    "Interval",
    "Jet",
    "LayoutItem",
    "LayoutPlacement",
    "LidSpec",
    "ManufacturingProfile",
    "Node",
    "NonlinearConstraint",
    "OpenAICompatiblePlanningProvider",
    "OrientationCandidate",
    "PCBSpec",
    "PreflightReport",
    "Primitive",
    "ProjectFormatError",
    "QuadraticToleranceStack",
    "Quantity",
    "ScoredOrientation",
    "SpecValidationReport",
    "StandoffSpec",
    "SteadyConductionInput",
    "ThermalExpansionInput",
    "ThinWallCylinderInput",
    "ToleranceContribution",
    "ToleranceStack",
    "ToleranceTerm",
    "Transform",
    "Unit",
    "ValidationReport",
    "VentPatternSpec",
    "apply_calibrated_clearance",
    "box",
    "build_enclosure",
    "build_project_bundle",
    "cone",
    "cylinder",
    "design_graph_to_ir",
    "design_to_scad",
    "edit_project_from_text",
    "euler_buckling",
    "fabrication_preflight",
    "fit_calibration_profile",
    "generate_design",
    "internal_pipe_flow",
    "interpret_enclosure",
    "interpret_provider_payload",
    "jet_cos",
    "jet_exp",
    "jet_log",
    "jet_sin",
    "jet_sqrt",
    "linear_system_diagnostics",
    "minimize_constrained",
    "monte_carlo_propagate",
    "pack_rectangles",
    "parse_agent_plan",
    "parse_calibration_dataset",
    "parse_calibration_profile",
    "parse_ir_json",
    "parse_project",
    "parse_unit",
    "plan_calibration_application",
    "plan_to_program",
    "planning_provider",
    "program_preview_svg",
    "program_semantic_form",
    "program_semantic_sha256",
    "program_to_scad",
    "programs_semantically_equivalent",
    "project_from_text",
    "quadratic_tolerance_stack",
    "quantity",
    "read_project",
    "rectangular_cantilever",
    "score_orientations",
    "semantic_diff",
    "serialize_calibration_dataset",
    "serialize_calibration_profile",
    "serialize_ir_json",
    "serialize_project",
    "solve_nonlinear_constraints",
    "sphere",
    "steady_conduction",
    "symmetric_positions",
    "thermal_expansion",
    "thin_wall_cylinder",
    "tolerance_stack",
    "torus",
    "update_project",
    "validate_design",
    "validate_enclosure_spec",
    "validate_program",
    "value_gradient_hessian",
    "write_project",
]
