from __future__ import annotations

import json
import secrets
import sys
import threading
import webbrowser
from functools import lru_cache
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any

from text_to_cad import TextToCAD

from .benchmark import generate_benchmark, run_benchmark
from .enclosure import build_enclosure
from .ir import CADProgram, program_node_bounds, validate_program
from .ir_export import program_to_scad
from .ir_parser import parse_ir_json
from .json_io import strict_json_loads
from .manufacturing import fabrication_preflight
from .natural_language import interpret_enclosure
from .program_evaluation import evaluate_program
from .project import enclosure_spec_to_dict

MAX_REQUEST_BYTES = 1_048_576
MAX_PROMPT_CHARACTERS = 4096


def _preview_svg(program: CADProgram) -> str:
    node_map = program.node_map()
    leaves = [node for node in program.nodes if node.primitive is not None]
    bounds = [program_node_bounds(node, node_map) for node in leaves]
    min_x = min(item[0][0] for item in bounds)
    max_x = max(item[1][0] for item in bounds)
    min_y = min(item[0][1] for item in bounds)
    max_y = max(item[1][1] for item in bounds)
    span_x = max(max_x - min_x, 1.0)
    span_y = max(max_y - min_y, 1.0)
    scale = min(680 / span_x, 360 / span_y)

    def point(x: float, y: float) -> tuple[float, float]:
        return 40 + (x - min_x) * scale, 40 + (max_y - y) * scale

    shapes: list[str] = []
    for node, (lower, upper) in sorted(zip(leaves, bounds, strict=True), key=lambda item: item[0].id):
        x, y = point(lower[0], upper[1])
        width = max((upper[0] - lower[0]) * scale, 2)
        height = max((upper[1] - lower[1]) * scale, 2)
        subtractive = node.role in {"cut", "void"} or node.id.startswith(("hole_", "slot_", "cavity"))
        fill = "#081018" if subtractive else "#26c6da"
        stroke = "#ff7b72" if subtractive else "#b2f5ff"
        if node.primitive and node.primitive.kind in {"cylinder", "sphere", "torus"}:
            shapes.append(
                f'<ellipse cx="{x + width / 2:.2f}" cy="{y + height / 2:.2f}" rx="{width / 2:.2f}" '
                f'ry="{height / 2:.2f}" fill="{fill}" stroke="{stroke}" stroke-width="2" />'
            )
        else:
            shapes.append(
                f'<rect x="{x:.2f}" y="{y:.2f}" width="{width:.2f}" height="{height:.2f}" '
                f'rx="4" fill="{fill}" stroke="{stroke}" stroke-width="2" />'
            )
    return (
        '<svg viewBox="0 0 760 440" role="img" aria-label="Deterministic top-view bounds preview" '
        'xmlns="http://www.w3.org/2000/svg"><rect width="760" height="440" rx="18" fill="#081018" />'
        '<g opacity=".2" stroke="#558"><path d="M0 220H760M380 0V440" /></g>'
        + "".join(shapes)
        + '<text x="20" y="422" fill="#8294a8" font-family="monospace" font-size="12">'
        "Preview: projected primitive bounds; export geometry is generated by OpenSCAD.</text></svg>"
    )


def generate_demo_payload(source: str, source_type: str = "prompt") -> dict[str, Any]:
    if not isinstance(source, str) or not source.strip():
        raise ValueError("source must be a non-empty string")
    if source_type == "enclosure":
        if len(source) > MAX_PROMPT_CHARACTERS:
            raise ValueError("engineering prompts are limited to 4096 characters")
        interpretation = interpret_enclosure(source)
        if not interpretation.ready or interpretation.spec is None:
            messages = [issue.message for issue in interpretation.issues]
            raise ValueError("; ".join(messages) or "enclosure requirements are incomplete")
        spec = interpretation.spec
        build = build_enclosure(spec)
        part_evaluations = {part: evaluate_program(program) for part, program in build.parts.items()}
        preflight = fabrication_preflight(spec)
        programs = {part: program.to_dict() for part, program in build.parts.items()}
        scad_parts = {part: program_to_scad(program) for part, program in build.parts.items()}
        return {
            "mode": "enclosure",
            "prompt": source,
            "spec": enclosure_spec_to_dict(spec),
            "mappings": [mapping.__dict__ for mapping in interpretation.mappings],
            "ir": programs,
            "validation": build.validation.to_dict(),
            "manufacturing": preflight.to_dict(),
            "evaluation": {
                "structural_validity": all(item.structural_validity for item in part_evaluations.values()),
                "kernel_validity": None,
                "editable_nodes": sum(item.editable_nodes for item in part_evaluations.values()),
                "evaluation_latency_ms": sum(item.evaluation_latency_ms for item in part_evaluations.values()),
            },
            "scad": scad_parts,
            "preview_svg": _preview_svg(build.body),
            "parts": sorted(build.parts),
        }
    if source_type == "ir":
        if len(source.encode("utf-8")) > MAX_REQUEST_BYTES:
            raise ValueError("canonical IR input is limited to 1 MiB")
        program = parse_ir_json(source)
        prompt = None
    elif source_type == "prompt":
        if len(source) > MAX_PROMPT_CHARACTERS:
            raise ValueError("engineering prompts are limited to 4096 characters")
        document = TextToCAD().build(source)
        if not document.validation.valid:
            raise ValueError("; ".join(document.validation.errors))
        program = document.require_program()
        prompt = document.prompt
    else:
        raise ValueError("source_type must be enclosure, prompt, or ir")
    report = validate_program(program)
    if not report.valid:
        raise ValueError("; ".join(issue.message for issue in report.errors))
    return {
        "mode": "canonical_program",
        "prompt": prompt,
        "ir": program.to_dict(),
        "validation": report.to_dict(),
        "evaluation": evaluate_program(program).to_dict(),
        "scad": program_to_scad(program),
        "preview_svg": _preview_svg(program),
    }


HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>NeuroCAD Enclosure Workbench</title><style nonce="__NONCE__">
:root{color-scheme:dark;--bg:#05090d;--panel:#0b131c;--line:#203140;--text:#e8f1f8;--muted:#8ba0b3;--cyan:#26c6da;--red:#ff7b72}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% 0,#102b35 0,transparent 36%),var(--bg);color:var(--text);font:15px/1.5 Inter,system-ui,sans-serif}
main{max-width:1240px;margin:auto;padding:38px 24px 70px}header{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:28px}h1{font-size:clamp(34px,6vw,72px);line-height:.9;margin:0;letter-spacing:-.06em}h1 span{color:var(--cyan)}header p{max-width:520px;color:var(--muted);margin:0}.grid{display:grid;grid-template-columns:minmax(300px,.85fr) minmax(380px,1.4fr);gap:18px}.panel{background:color-mix(in srgb,var(--panel) 93%,transparent);border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 20px 60px #0005}label{display:block;color:var(--muted);margin-bottom:7px;font-weight:600}textarea,select{width:100%;border:1px solid var(--line);border-radius:10px;background:#071018;color:var(--text);padding:12px;font:13px/1.5 ui-monospace,monospace}textarea{min-height:220px;resize:vertical}select{font-family:inherit;margin-bottom:12px}button{width:100%;padding:13px;border:0;border-radius:10px;background:var(--cyan);color:#031014;font-weight:800;cursor:pointer;margin-top:12px}button:disabled{opacity:.5;cursor:wait}.status{min-height:25px;margin:12px 0 0;color:var(--muted)}.error{color:var(--red)}#preview svg{width:100%;height:auto;display:block}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.metric{background:#071018;border:1px solid var(--line);border-radius:10px;padding:10px}.metric b{display:block;font-size:18px;color:var(--cyan)}.metric small{color:var(--muted)}details{margin-top:14px;border-top:1px solid var(--line);padding-top:12px}summary{cursor:pointer;font-weight:700}pre{overflow:auto;max-height:380px;background:#050a0f;border-radius:10px;padding:13px;font:12px/1.5 ui-monospace,monospace;color:#c4d7e8}@media(max-width:800px){header{display:block}header p{margin-top:18px}.grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}}
</style></head><body><main><header><h1>Neuro<span>CAD</span></h1><p>Design a bounded electronics enclosure, inspect every interpreted field, review fabrication warnings, and export deterministic OpenSCAD without hidden defaults.</p></header>
<div class="grid"><section class="panel"><label for="sourceType">Input contract</label><select id="sourceType"><option value="enclosure">Electronics enclosure requirements</option><option value="prompt">Basic supported geometry prompt</option><option value="ir">Canonical NeuroCAD IR JSON</option></select><label for="source">Input</label><textarea id="source">80 x 60 x 30 mm electronics enclosure; walls 2 mm; profile fdm standard; friction lid 2.5 mm thick clearance 0.3 mm lip 2 mm; rectangular cutout 12 x 7 mm on front at 0 x 8 mm for USB-C; title controller case</textarea><button id="generate">Interpret, validate &amp; preview</button><p id="status" class="status" aria-live="polite"></p></section>
<section class="panel"><div id="preview"></div><div id="metrics" class="metrics"></div><details open><summary>Interpreted specification / canonical IR</summary><pre id="ir"></pre></details><details><summary>OpenSCAD exports</summary><pre id="scad"></pre></details><details><summary>Validation and fabrication preflight</summary><pre id="validation"></pre></details></section></div></main>
<script nonce="__NONCE__">
const source=document.querySelector('#source'),type=document.querySelector('#sourceType'),button=document.querySelector('#generate'),status=document.querySelector('#status');
const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function run(){button.disabled=true;status.className='status';status.textContent='Running the real pipeline…';try{const response=await fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source:source.value,source_type:type.value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Generation failed');document.querySelector('#preview').innerHTML=data.preview_svg;const e=data.evaluation;const kernel=e.kernel_validity===null?'unverified':e.kernel_validity;document.querySelector('#metrics').innerHTML=[['Structurally valid',e.structural_validity],['Kernel geometry',kernel],['Editable nodes',e.editable_nodes],['Latency',e.evaluation_latency_ms.toFixed(2)+' ms']].map(x=>`<div class="metric"><b>${esc(x[1])}</b><small>${esc(x[0])}</small></div>`).join('');document.querySelector('#ir').textContent=JSON.stringify(data.spec||data.ir,null,2);document.querySelector('#scad').textContent=typeof data.scad==='string'?data.scad:JSON.stringify(data.scad,null,2);document.querySelector('#validation').textContent=JSON.stringify({validation:data.validation,manufacturing:data.manufacturing||null},null,2);status.textContent=data.mode==='enclosure'?'Enclosure specification is complete; review warnings before compiling or fabrication.':'Validated canonical program generated; compile an STL for kernel geometry verification.'}catch(error){status.className='status error';status.textContent=error.message}finally{button.disabled=false}}
button.addEventListener('click',run);type.addEventListener('change',()=>{if(type.value==='enclosure')source.value='80 x 60 x 30 mm electronics enclosure; walls 2 mm; profile fdm standard; friction lid 2.5 mm thick clearance 0.3 mm lip 2 mm; rectangular cutout 12 x 7 mm on front at 0 x 8 mm for USB-C; title controller case';else if(type.value==='prompt')source.value='a 120 x 80 x 4 mm plate with four 4 mm holes';else source.value='Paste canonical NeuroCAD IR JSON here';});run();
</script></body></html>"""


class DemoHandler(BaseHTTPRequestHandler):
    server_version = "NeuroCADDemo/1"

    def _json(self, status: HTTPStatus, value: dict[str, Any]) -> None:
        body = json.dumps(value, sort_keys=True).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("X-Frame-Options", "DENY")
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:
        if self.path == "/":
            nonce = secrets.token_urlsafe(18)
            body = HTML.replace("__NONCE__", nonce).encode("utf-8")
            self.send_response(HTTPStatus.OK)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("X-Content-Type-Options", "nosniff")
            self.send_header("Referrer-Policy", "no-referrer")
            self.send_header("X-Frame-Options", "DENY")
            self.send_header("Permissions-Policy", "camera=(), microphone=(), geolocation=()")
            self.send_header(
                "Content-Security-Policy",
                f"default-src 'none'; connect-src 'self'; img-src 'self' data:; style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'",
            )
            self.end_headers()
            self.wfile.write(body)
        elif self.path == "/api/health":
            self._json(HTTPStatus.OK, {"status": "ok", "service": "neurocad-demo"})
        elif self.path == "/api/benchmark":
            self._json(HTTPStatus.OK, _benchmark_payload())
        else:
            self._json(HTTPStatus.NOT_FOUND, {"error": "not found"})

    def do_POST(self) -> None:
        if self.path != "/api/generate":
            self._json(HTTPStatus.NOT_FOUND, {"error": "not found"})
            return
        try:
            content_type = self.headers.get("Content-Type", "").partition(";")[0].strip().lower()
            if content_type != "application/json":
                self._json(HTTPStatus.UNSUPPORTED_MEDIA_TYPE, {"error": "Content-Type must be application/json"})
                return
            length = int(self.headers.get("Content-Length", "0"))
            if length <= 0 or length > MAX_REQUEST_BYTES:
                raise ValueError("request body must be between 1 byte and 1 MiB")
            request = strict_json_loads(self.rfile.read(length).decode("utf-8"))
            if not isinstance(request, dict):
                raise TypeError("request body must be a JSON object")
            source = request.get("source")
            if not isinstance(source, str):
                raise TypeError("source must be a string")
            payload = generate_demo_payload(source, request.get("source_type", "prompt"))
        except (ValueError, TypeError, json.JSONDecodeError) as exc:
            self._json(HTTPStatus.BAD_REQUEST, {"error": str(exc)})
            return
        self._json(HTTPStatus.OK, payload)

    def log_message(self, format: str, *args: object) -> None:
        return


@lru_cache(maxsize=1)
def _benchmark_payload() -> dict[str, Any]:
    return run_benchmark(generate_benchmark())


class DemoServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True


def serve_demo(host: str = "127.0.0.1", port: int = 8765, *, open_browser: bool = True) -> None:
    if not 1 <= port <= 65535:
        raise ValueError("port must be between 1 and 65535")
    server = DemoServer((host, port), DemoHandler)
    url = f"http://{host}:{port}/"
    print(f"NeuroCAD demo running at {url}")
    if host not in {"127.0.0.1", "localhost", "::1"}:
        print("WARNING: the unauthenticated demo is listening beyond the loopback interface", file=sys.stderr)
    if open_browser:
        threading.Timer(0.3, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nNeuroCAD demo stopped.")
    finally:
        server.server_close()
