from __future__ import annotations

import hashlib
import ipaddress
import json
import secrets
import socket
import sys
import threading
import webbrowser
from functools import lru_cache
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, cast

from text_to_cad import TextToCAD

from .artifacts import CompilerTimeoutError, CompilerUnavailableError
from .benchmark import generate_benchmark, run_benchmark
from .edit_language import edit_project_from_text
from .enclosure import build_enclosure
from .ir import CADProgram, program_node_bounds, validate_program
from .ir_export import program_to_scad
from .ir_parser import parse_ir_json
from .json_io import strict_json_loads
from .manufacturing import fabrication_preflight
from .mesh_preview import DOWNLOADS, CompilerBusyError, compile_payload_meshes
from .natural_language import interpret_enclosure
from .program_evaluation import evaluate_program
from .project import enclosure_spec_to_dict, parse_project, semantic_diff, serialize_project
from .workbench import HTML
from .workflow import project_from_interpretation

MAX_REQUEST_BYTES = 1_048_576
MAX_PROMPT_CHARACTERS = 4096
LOOPBACK_HOSTS = frozenset({"127.0.0.1", "localhost", "::1"})


def _is_loopback_host(host: str) -> bool:
    normalized = host.strip().lower()
    if normalized == "localhost":
        return True
    try:
        return ipaddress.ip_address(normalized).is_loopback
    except ValueError:
        return False


def _preview_svg(program: CADProgram) -> str:
    node_map = program.node_map()
    leaves = [node for node in program.nodes if node.primitive is not None]
    bounds = [program_node_bounds(node, node_map) for node in leaves]
    min_x = min(item[0][0] for item in bounds)
    max_x = max(item[1][0] for item in bounds)
    min_y = min(item[0][1] for item in bounds)
    max_y = max(item[1][1] for item in bounds)
    span_x = max(max_x - min_x, 1.0)
    span_y = max(max_y - min_y, 1.0)
    scale = min(680 / span_x, 360 / span_y)

    def point(x: float, y: float) -> tuple[float, float]:
        return 40 + (x - min_x) * scale, 40 + (max_y - y) * scale

    shapes: list[str] = []
    for node, (lower, upper) in sorted(zip(leaves, bounds, strict=True), key=lambda item: item[0].id):
        x, y = point(lower[0], upper[1])
        width = max((upper[0] - lower[0]) * scale, 2)
        height = max((upper[1] - lower[1]) * scale, 2)
        subtractive = node.role in {"cut", "void"} or node.id.startswith(("hole_", "slot_", "cavity"))
        fill = "#081018" if subtractive else "#26c6da"
        stroke = "#ff7b72" if subtractive else "#b2f5ff"
        if node.primitive and node.primitive.kind in {"cylinder", "sphere", "torus"}:
            shapes.append(
                f'<ellipse cx="{x + width / 2:.2f}" cy="{y + height / 2:.2f}" rx="{width / 2:.2f}" '
                f'ry="{height / 2:.2f}" fill="{fill}" stroke="{stroke}" stroke-width="2" />'
            )
        else:
            shapes.append(
                f'<rect x="{x:.2f}" y="{y:.2f}" width="{width:.2f}" height="{height:.2f}" '
                f'rx="4" fill="{fill}" stroke="{stroke}" stroke-width="2" />'
            )
    return (
        '<svg viewBox="0 0 760 440" role="img" aria-label="Deterministic top-view bounds preview" '
        'xmlns="http://www.w3.org/2000/svg"><rect width="760" height="440" rx="18" fill="#081018" />'
        '<g opacity=".2" stroke="#558"><path d="M0 220H760M380 0V440" /></g>'
        + "".join(shapes)
        + '<text x="20" y="422" fill="#8294a8" font-family="monospace" font-size="12">'
        "Preview: projected primitive bounds; export geometry is generated by OpenSCAD.</text></svg>"
    )


def generate_demo_payload(source: str, source_type: str = "prompt") -> dict[str, Any]:
    if not isinstance(source, str) or not source.strip():
        raise ValueError("source must be a non-empty string")
    if source_type in ("enclosure", "project"):
        if source_type == "project":
            project = parse_project(source)
        else:
            if len(source) > MAX_PROMPT_CHARACTERS:
                raise ValueError("engineering prompts are limited to 4096 characters")
            interpretation = interpret_enclosure(source)
            if not interpretation.ready or interpretation.spec is None:
                messages = [issue.message for issue in interpretation.issues]
                raise ValueError("; ".join(messages) or "enclosure requirements are incomplete")
            project = project_from_interpretation("workbench-enclosure", interpretation)
        spec = project.spec
        build = build_enclosure(spec)
        part_evaluations = {part: evaluate_program(program) for part, program in build.parts.items()}
        preflight = fabrication_preflight(spec)
        programs = {part: program.to_dict() for part, program in build.parts.items()}
        scad_parts = {part: program_to_scad(program) for part, program in build.parts.items()}
        return {
            "mode": "enclosure",
            "prompt": project.source_text,
            "project": project.to_dict(),
            "spec": enclosure_spec_to_dict(spec),
            "mappings": [mapping.__dict__ for mapping in project.phrase_mappings],
            "ir": programs,
            "validation": build.validation.to_dict(),
            "manufacturing": preflight.to_dict(),
            "evaluation": {
                "structural_validity": all(item.structural_validity for item in part_evaluations.values()),
                "kernel_validity": None,
                "editable_nodes": sum(item.editable_nodes for item in part_evaluations.values()),
                "evaluation_latency_ms": sum(item.evaluation_latency_ms for item in part_evaluations.values()),
            },
            "scad": scad_parts,
            "preview_svg": _preview_svg(build.body),
            "parts": sorted(build.parts),
        }
    if source_type == "ir":
        if len(source.encode("utf-8")) > MAX_REQUEST_BYTES:
            raise ValueError("canonical IR input is limited to 1 MiB")
        program = parse_ir_json(source)
        prompt = None
    elif source_type == "prompt":
        if len(source) > MAX_PROMPT_CHARACTERS:
            raise ValueError("engineering prompts are limited to 4096 characters")
        document = TextToCAD().build(source)
        if not document.validation.valid:
            raise ValueError("; ".join(document.validation.errors))
        program = document.require_program()
        prompt = document.prompt
    else:
        raise ValueError("source_type must be enclosure, project, prompt, or ir")
    report = validate_program(program)
    if not report.valid:
        raise ValueError("; ".join(issue.message for issue in report.errors))
    return {
        "mode": "canonical_program",
        "prompt": prompt,
        "ir": program.to_dict(),
        "validation": report.to_dict(),
        "evaluation": evaluate_program(program).to_dict(),
        "scad": program_to_scad(program),
        "preview_svg": _preview_svg(program),
    }



def preview_project_edit(source: str, instruction: str, reason: str | None = None) -> dict[str, Any]:
    """Return a validated proposed revision; the server never mutates a project.

    Use the same parser, edit grammar and history contract as the installed CLI.
    The browser must explicitly accept the proposal before replacing its input.
    """
    project = parse_project(source)
    revised = edit_project_from_text(project, instruction, reason=reason)
    changes = semantic_diff(project, revised)
    if not changes:
        raise ValueError("edit makes no change to the current specification")
    payload = generate_demo_payload(serialize_project(revised), "project")
    payload["edit"] = {
        "base_revision": project.revision,
        "base_project_sha256": hashlib.sha256(serialize_project(project).encode("utf-8")).hexdigest(),
        "changes": list(changes),
        "reason": revised.changes[-1].reason,
    }
    return payload


class DemoHandler(BaseHTTPRequestHandler):
    server_version = "NeuroCADDemo/1"

    def _json(self, status: HTTPStatus, value: dict[str, Any], *, retry_after: int | None = None) -> None:
        body = json.dumps(value, sort_keys=True).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("X-Frame-Options", "DENY")
        if retry_after is not None:
            self.send_header("Retry-After", str(retry_after))
        self.end_headers()
        self.wfile.write(body)

    def _host_header_allowed(self) -> bool:
        if not getattr(self.server, "enforce_loopback_host_header", True):
            return True
        if len(self.headers.get_all("Host", [])) != 1:
            return False
        supplied = self.headers.get("Host", "").strip().lower()
        if not supplied:
            return False
        port = cast("DemoServer", self.server).server_port
        allowed = {f"{host}:{port}" for host in LOOPBACK_HOSTS if ":" not in host}
        allowed.add(f"[::1]:{port}")
        return supplied in allowed

    def _reject_bad_host(self) -> bool:
        if self._host_header_allowed():
            return False
        self._json(HTTPStatus.MISDIRECTED_REQUEST, {"error": "unrecognized Host header"})
        return True

    def do_GET(self) -> None:
        if self._reject_bad_host():
            return
        if self.path == "/":
            nonce = secrets.token_urlsafe(18)
            body = HTML.replace("__NONCE__", nonce).encode("utf-8")
            self.send_response(HTTPStatus.OK)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("X-Content-Type-Options", "nosniff")
            self.send_header("Referrer-Policy", "no-referrer")
            self.send_header("X-Frame-Options", "DENY")
            self.send_header("Permissions-Policy", "camera=(), microphone=(), geolocation=()")
            self.send_header(
                "Content-Security-Policy",
                f"default-src 'none'; connect-src 'self'; img-src 'self' data:; style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'",
            )
            self.end_headers()
            self.wfile.write(body)
        elif self.path == "/api/health":
            self._json(HTTPStatus.OK, {"status": "ok", "service": "neurocad-demo"})
        elif self.path.startswith('/api/mesh/'):
            raw = DOWNLOADS.get(self.path)
            if raw is None:
                self._json(HTTPStatus.NOT_FOUND, {"error": "Download expired or unavailable; compile again"})
                return
            self.send_response(HTTPStatus.OK)
            self.send_header('Content-Type', 'model/stl')
            self.send_header('Content-Disposition', 'attachment; filename="neurocad.stl"')
            self.send_header('Content-Length', str(len(raw)))
            self.send_header('Cache-Control', 'no-store')
            self.send_header('X-Content-Type-Options', 'nosniff')
            self.end_headers()
            self.wfile.write(raw)
        elif self.path == "/api/benchmark":
            self._json(HTTPStatus.OK, _benchmark_payload())
        else:
            self._json(HTTPStatus.NOT_FOUND, {"error": "not found"})

    def do_POST(self) -> None:
        if self._reject_bad_host():
            return
        origins = self.headers.get_all("Origin", [])
        if origins and (len(origins) != 1 or origins[0] not in {
            f"http://{self.headers.get('Host', '')}", f"https://{self.headers.get('Host', '')}",
        }):
            self._json(HTTPStatus.FORBIDDEN, {"error": "cross-origin requests are not allowed"})
            return
        if self.path not in {"/api/generate", "/api/edit"}:
            self._json(HTTPStatus.NOT_FOUND, {"error": "not found"})
            return
        try:
            content_type = self.headers.get("Content-Type", "").partition(";")[0].strip().lower()
            if len(self.headers.get_all("Content-Type", [])) != 1 or content_type != "application/json":
                self._json(HTTPStatus.UNSUPPORTED_MEDIA_TYPE, {"error": "Content-Type must be application/json"})
                return
            if self.headers.get_all("Transfer-Encoding") or len(self.headers.get_all("Content-Length", [])) != 1:
                raise ValueError("request requires one Content-Length and no Transfer-Encoding")
            length = int(self.headers.get("Content-Length", "0"))
            if length <= 0 or length > MAX_REQUEST_BYTES:
                raise ValueError("request body must be between 1 byte and 1 MiB")
            raw = self.rfile.read(length)
            if len(raw) != length:
                raise ValueError("request body ended before Content-Length")
            request = strict_json_loads(raw.decode("utf-8"))
            if not isinstance(request, dict):
                raise TypeError("request body must be a JSON object")
            allowed = {"source", "instruction", "reason"} if self.path == "/api/edit" else {
                "source", "source_type", "compile_mesh", "timeout_seconds",
            }
            if request.keys() - allowed:
                raise ValueError("request contains unsupported fields")
            source = request.get("source")
            if not isinstance(source, str):
                raise TypeError("source must be a string")
            if self.path == "/api/edit":
                instruction, reason = request.get("instruction"), request.get("reason")
                if not isinstance(instruction, str):
                    raise TypeError("instruction must be a string")
                if reason is not None and not isinstance(reason, str):
                    raise TypeError("reason must be a string or null")
                payload = preview_project_edit(source, instruction, reason)
            else:
                compile_mesh = request.get("compile_mesh", False)
                if not isinstance(compile_mesh, bool):
                    raise TypeError("compile_mesh must be a boolean")
                timeout_seconds = request.get("timeout_seconds", 30)
                if type(timeout_seconds) is not int or timeout_seconds not in {30, 60, 120}:
                    raise ValueError("timeout_seconds must be 30, 60, or 120 seconds per part")
                payload = generate_demo_payload(source, request.get("source_type", "prompt"))
                if compile_mesh:
                    payload = compile_payload_meshes(payload, timeout_seconds=timeout_seconds)
                    DOWNLOADS.publish(payload['mesh_artifacts'])
        except CompilerTimeoutError:
            self._json(HTTPStatus.GATEWAY_TIMEOUT, {
                "error": "OpenSCAD exceeded the selected per-part deadline. Wait for system load to settle, explicitly select a longer compile budget, or use the CLI with --timeout. No new mesh was published.",
                "code": "compiler_timeout",
            })
            return
        except CompilerUnavailableError:
            self._json(HTTPStatus.SERVICE_UNAVAILABLE, {
                "error": "OpenSCAD was not found. Install it and make its executable available on PATH; source/project downloads do not require it.",
                "code": "compiler_unavailable",
            })
            return
        except TimeoutError:
            self._json(HTTPStatus.REQUEST_TIMEOUT, {"error": "request body timed out"})
            return
        except CompilerBusyError as exc:
            self._json(HTTPStatus.SERVICE_UNAVAILABLE, {"error": str(exc)}, retry_after=5)
            return
        except (ValueError, TypeError, json.JSONDecodeError) as exc:
            self._json(HTTPStatus.BAD_REQUEST, {"error": str(exc)})
            return
        except (RuntimeError, OSError):
            self._json(HTTPStatus.SERVICE_UNAVAILABLE, {"error": "Mesh compilation failed. Check that OpenSCAD is installed, or use the CLI for diagnostics."})
            return
        self._json(HTTPStatus.OK, payload)

    def log_message(self, format: str, *args: object) -> None:
        return


@lru_cache(maxsize=1)
def _benchmark_payload() -> dict[str, Any]:
    return run_benchmark(generate_benchmark())


class DemoServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True
    enforce_loopback_host_header = True
    request_timeout_seconds = 10.0
    maximum_workers = 8

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self._worker_slots = threading.BoundedSemaphore(self.maximum_workers)
        super().__init__(*args, **kwargs)

    def get_request(self) -> tuple[socket.socket, Any]:
        request, address = super().get_request()
        request.settimeout(self.request_timeout_seconds)
        return request, address

    def process_request(self, request: socket.socket | tuple[bytes, socket.socket], client_address: Any) -> None:
        if not self._worker_slots.acquire(blocking=False):
            # Do not block the accept loop or create a worker for overload.
            self.shutdown_request(request)
            return
        try:
            super().process_request(request, client_address)
        except Exception:
            self._worker_slots.release()
            raise

    def process_request_thread(self, request: socket.socket | tuple[bytes, socket.socket], client_address: Any) -> None:
        try:
            super().process_request_thread(request, client_address)
        finally:
            self._worker_slots.release()


def serve_demo(
    host: str = "127.0.0.1",
    port: int = 8765,
    *,
    open_browser: bool = True,
    allow_remote: bool = False,
) -> None:
    if not 1 <= port <= 65535:
        raise ValueError("port must be between 1 and 65535")
    loopback = _is_loopback_host(host)
    if not loopback and not allow_remote:
        raise ValueError("non-loopback demo binding requires explicit allow_remote=True / --allow-remote")
    server_class = DemoServer
    if ":" in host:
        class IPv6DemoServer(DemoServer):
            address_family = socket.AF_INET6

        server_class = IPv6DemoServer
    server = server_class((host, port), DemoHandler)
    server.enforce_loopback_host_header = loopback
    url_host = f"[{host}]" if ":" in host else host
    url = f"http://{url_host}:{port}/"
    print(f"NeuroCAD demo running at {url}")
    if not loopback:
        print("WARNING: the unauthenticated demo is listening beyond the loopback interface", file=sys.stderr)
    if open_browser:
        threading.Timer(0.3, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nNeuroCAD demo stopped.")
    finally:
        server.server_close()
