from __future__ import annotations

import math
from typing import Any, Dict, Iterable, List, Sequence

from .design_graph import Component, DesignGraph


def _fmt_num(value: float) -> str:
    if isinstance(value, int):
        return str(value)
    value = float(value)
    if math.isfinite(value) and abs(value - round(value)) < 1e-9:
        return str(int(round(value)))
    return f"{value:.6f}".rstrip("0").rstrip(".")


def _fmt_vec(vec: Sequence[float]) -> str:
    return "[" + ", ".join(_fmt_num(v) for v in vec) + "]"


def _primitive_scad(geometry: Dict[str, Any]) -> str:
    kind = (geometry.get("kind") or "box").lower()

    if kind in {"box", "cube"}:
        size = geometry.get("size") or (
            geometry.get("w", 1.0),
            geometry.get("h", 1.0),
            geometry.get("d", 1.0),
        )
        center = bool(geometry.get("center", True))
        return f"cube(size={_fmt_vec(size)}, center={'true' if center else 'false'});"

    if kind == "sphere":
        r = geometry.get("radius", geometry.get("r", 1.0))
        return f"sphere(r={_fmt_num(r)});"

    if kind in {"cylinder", "tube"}:
        h = geometry.get("height", geometry.get("h", 1.0))
        center = bool(geometry.get("center", True))
        if "radius" in geometry or "r" in geometry:
            r = geometry.get("radius", geometry.get("r", 1.0))
            return f"cylinder(r={_fmt_num(r)}, h={_fmt_num(h)}, center={'true' if center else 'false'});"
        if "diameter" in geometry or "d" in geometry:
            d = geometry.get("diameter", geometry.get("d", 1.0))
            return f"cylinder(d={_fmt_num(d)}, h={_fmt_num(h)}, center={'true' if center else 'false'});"
        return f"cylinder(r={_fmt_num(geometry.get('radius', 1.0))}, h={_fmt_num(h)}, center={'true' if center else 'false'});"

    if kind == "cone":
        r1 = geometry.get("r1", geometry.get("radius1", geometry.get("radius", 1.0)))
        r2 = geometry.get("r2", geometry.get("radius2", 0.0))
        h = geometry.get("height", geometry.get("h", 1.0))
        center = bool(geometry.get("center", True))
        return f"cylinder(r1={_fmt_num(r1)}, r2={_fmt_num(r2)}, h={_fmt_num(h)}, center={'true' if center else 'false'});"

    if kind == "torus":
        R = geometry.get("R", 1.0)
        r = geometry.get("r", 0.25)
        return (
            f"rotate_extrude(convexity=10) translate([{_fmt_num(R)}, 0, 0]) "
            f"circle(r={_fmt_num(r)});"
        )

    if kind == "text":
        txt = geometry.get("text", "CAD")
        size = geometry.get("size", 10)
        return f'text(text={txt!r}, size={_fmt_num(size)});'

    raise ValueError(f"Unsupported geometry kind: {kind}")


def _apply_transform(scad: str, transform: Dict[str, Sequence[float]]) -> str:
    result = scad
    scale = tuple(transform.get("scale", (1.0, 1.0, 1.0)))
    rotate = tuple(transform.get("rotate", (0.0, 0.0, 0.0)))
    translate = tuple(transform.get("translate", (0.0, 0.0, 0.0)))

    if any(abs(v - 1.0) > 1e-12 for v in scale):
        result = f"scale({_fmt_vec(scale)}) {{\n{_indent(result)}\n}}"

    if any(abs(v) > 1e-12 for v in rotate):
        result = f"rotate({_fmt_vec(rotate)}) {{\n{_indent(result)}\n}}"

    if any(abs(v) > 1e-12 for v in translate):
        result = f"translate({_fmt_vec(translate)}) {{\n{_indent(result)}\n}}"

    return result


def _indent(text: str, spaces: int = 2) -> str:
    pad = " " * spaces
    return "\n".join((pad + line) if line else line for line in text.splitlines())


def render_component(component: Component) -> str:
    geometry = component.params.get("geometry")
    if not geometry:
        raise ValueError(f"Component {component.name!r} does not include geometry")
    body = _primitive_scad(geometry)
    body = _apply_transform(body, component.transform)
    return f"// component: {component.name} ({component.role})\n{body}\n"


def design_to_scad(design: DesignGraph, *, fn: int = 96) -> str:
    positives: List[str] = []
    negatives: List[str] = []

    for component in design.components:
        rendered = render_component(component)
        if component.operation == "difference":
            negatives.append(rendered)
        elif component.operation == "intersection":
            # Keep intersection support as a direct block.
            positives.append(("intersection", rendered))
        else:
            positives.append(rendered)

    lines = [
        "// ========================================",
        f"// {design.title}",
        "// Generated by cad-agent text-to-CAD",
        "// ========================================",
        f"$fn = {int(fn)};",
        "",
    ]

    if any(isinstance(item, tuple) and item[0] == "intersection" for item in positives):
        inter_items = [item[1] for item in positives if isinstance(item, tuple) and item[0] == "intersection"]
        lines.append("intersection() {")
        for block in inter_items:
            lines.append(_indent(block.rstrip()))
        lines.append("}")
    elif negatives:
        lines.append("difference() {")
        lines.append(_indent("union() {"))
        for block in positives:
            if isinstance(block, str):
                lines.append(_indent(_indent(block.rstrip())))
        lines.append(_indent("}"))
        for block in negatives:
            lines.append(_indent(block.rstrip()))
        lines.append("}")
    else:
        lines.append("union() {")
        for block in positives:
            if isinstance(block, str):
                lines.append(_indent(block.rstrip()))
        lines.append("}")

    return "\n".join(lines).rstrip() + "\n"
