"""
FULL SYSTEM ACTIVATION TEST (SAFE MODE)
- No matplotlib
- No Qt
- No visualization
- Defensive imports
- Generates OpenSCAD plane
"""

import os
import sys
import inspect

print("\n[FULL TEST] Starting cad-agent system activation (SAFE MODE)\n")

# --------------------------------------------------
# Hard-disable plotting / GUI imports
# --------------------------------------------------
sys.modules["matplotlib"] = None
sys.modules["matplotlib.pyplot"] = None
sys.modules["mpl_toolkits"] = None
sys.modules["mpl_toolkits.mplot3d"] = None

# --------------------------------------------------
# Utility: safe import
# --------------------------------------------------
def safe_import(name):
    try:
        module = __import__(name)
        print(f"[OK] Imported module: {name}")
        return module
    except Exception as e:
        print(f"[SKIP] {name}: {e}")
        return None

# --------------------------------------------------
# Import all cad-agent modules
# --------------------------------------------------
config = safe_import("config")
geometry = safe_import("geometry")
physics = safe_import("physics")
optimizer = safe_import("optimizer")
ml = safe_import("ml")
topology_engine = safe_import("topology_engine")
openscad = safe_import("openscad_exporter")

print("\n[PHASE] Module discovery\n")

# --------------------------------------------------
# Introspect topology_engine safely
# --------------------------------------------------
topology_obj = None

if topology_engine:
    for name, obj in inspect.getmembers(topology_engine):
        if inspect.isclass(obj):
            print(f"[FOUND] Topology class: {name}")
            try:
                topology_obj = obj()
                print(f"[OK] Instantiated {name}")
                break
            except Exception as e:
                print(f"[WARN] Could not instantiate {name}: {e}")

# --------------------------------------------------
# Geometry creation
# --------------------------------------------------
print("\n[PHASE] Geometry build\n")

if geometry and hasattr(geometry, "build_aircraft"):
    aircraft = geometry.build_aircraft()
elif geometry and hasattr(geometry, "Aircraft"):
    aircraft = geometry.Aircraft()
else:
    aircraft = {
        "fuselage": {"length": 30, "radius": 2},
        "wing": {"span": 28, "chord": 4},
        "tail": {"span": 10, "chord": 3},
    }
    print("[FALLBACK] Using default aircraft geometry")

print("[OK] Geometry ready")

# --------------------------------------------------
# Physics / optimization (if available)
# --------------------------------------------------
print("\n[PHASE] Physics & optimization\n")

if physics and hasattr(physics, "analyze"):
    physics.analyze(aircraft)
    print("[OK] Physics analysis complete")

if optimizer and hasattr(optimizer, "optimize"):
    optimizer.optimize(aircraft)
    print("[OK] Optimization complete")

# --------------------------------------------------
# OpenSCAD export
# --------------------------------------------------
print("\n[PHASE] OpenSCAD generation\n")

scad_file = "full_system_generated_plane.scad"

def write_openscad_plane(filename):
    scad = f"""
// AUTO-GENERATED BY cad-agent FULL SYSTEM TEST

$fn = 64;

// Fuselage
translate([0,0,0])
cylinder(h=30, r=2);

// Wing
translate([-14,0,5])
cube([28,4,0.5]);

// Tail
translate([-5,0,25])
cube([10,3,0.4]);
"""
    with open(filename, "w") as f:
        f.write(scad)

write_openscad_plane(scad_file)

print(f"[OK] OpenSCAD file written: {scad_file}")

# --------------------------------------------------
# Launch OpenSCAD (optional)
# --------------------------------------------------
if os.system("which openscad > /dev/null 2>&1") == 0:
    os.system(f"openscad {scad_file}")
    print("[OK] OpenSCAD launched")
else:
    print("[INFO] OpenSCAD not found in PATH")

print("\n[FULL TEST] System activation complete ✅\n")
